added hex logo to the package
philip-khor/bnmr pull request #19
Opened 2021-10-01 04:59 UTC by zatch3301

let me know if the logo is okay or do you need any changes to it.
![logo](https://user-images.githubusercontent.com/46402550/135567479-8d18bae6-be6b-4960-8b18-327c6535cbe5.png)

2021-10-01 16:54 UTC, philip-khor requested changes

2021-10-01 16:54 UTC, philip-khor commented on README.md
>  <!-- README.md is generated from README.Rmd. Please edit that file -->
Please edit README.Rmd and then knit.

2021-10-01 17:37 UTC, philip-khor requested changes
overall design looks good to me, perhaps you could try to use a dark shade of blue for the background instead of brown? should not be the exact tone of blue as the Bank's logo to avoid confusion that this is an official package.

![image](https://user-images.githubusercontent.com/35039795/135663319-bb26e990-6748-4b2a-b66f-bdeb957a257a.png)

2021-10-01 19:11 UTC, zatch3301 commented
![logo](https://user-images.githubusercontent.com/46402550/135674220-1adba58a-c0e6-498b-8df3-b6c3b332e1aa.png)

2021-10-02 04:47 UTC, merged

2021-10-02 04:47 UTC, philip-khor commented
looks good to me, thanks!