Update GH Actions workflow, add unit testing for input errors, and other miscellaneous changes
philip-khor/bnmr pull request #3
Opened 2020-10-06 23:18 UTC by HaydenMacDonald

I've made several changes to this package which I've documented below. Please let me know your thoughts! Note that I've added `\dontrun{}` tags around examples that are currently problematic (e.g. they return errors *sometimes*). 

Github Actions workflow
- Add support for multiple OSs

Testing
- Introduce tests for each function to boost codecov score to ~100%
- Add `\dontrun{}` tags on particular examples that were failing

Miscellaneous
- Chang `.onLoad` function to `.onAttach` to avoid RCMDCHECK notes
- Import .data from `rlang` to avoid notes associated with `tidy_select()`
- Add `as_tibble()` to `opr()` with default values

2020-10-12 13:33 UTC, HaydenMacDonald commented
Hey, @philip-khor! Let me know if you have any feedback regarding this pull request. I am happy to amend some of these changes if they don't fit with the original vision for the package. Thanks!

2020-10-12 13:39 UTC, philip-khor commented
Hi @HaydenMacDonald, sorry I missed this! Thanks for contributing, weirdly enough the diffs are pretty huge, but from the looks of it these look like minor changes. I'll try to get through this ASAP :)

2020-10-12 13:42 UTC, philip-khor commented on R/currencies.R
> +#' \dontrun{renminbi(type = "dar")}
LGTM, thanks for this addition! Afaik the API returns errors when there's too many calls, I've been meaning to write in to see if they'd up the limit for requests from this package, but I don't think the usage of this package is high enough to justify :)

2020-10-12 13:53 UTC, philip-khor requested changes
Great stuff, thanks! Minor nitpick:

2020-10-12 13:53 UTC, philip-khor commented on R/monthly.R
> +      stopifnot(is.numeric(year) & is.numeric(month))
```suggestion
      stopifnot(is.numeric(year) && is.numeric(month))

```

2020-10-12 13:53 UTC, philip-khor commented on R/monthly.R
> +      stopifnot(is.numeric(year) & is.numeric(month))
we should expect year and month of length 1 here, I was trying to extend the functionality to accept vectors but from line 30 I didn't quite get there for this function

2020-10-12 14:05 UTC, philip-khor approved these changes

2020-10-12 14:06 UTC, merged

2020-10-12 14:11 UTC, HaydenMacDonald commented
Cheers! Happy to contribute 🙂

2020-10-13 02:24 UTC, philip-khor commented
Btw can I check why the lubridate package was needed in this case? I don't recall having any dependencies on lubridate in the package functions ... would prefer to import just the functions we need rather than the entire package, in which case 'suggests' would be more suitable.

2020-10-14 10:24 UTC, HaydenMacDonald commented
I checked through the tests and R files. The lubridate package was likely part of a change that didn't make it to this pull request. Feel free to remove it!

2020-10-14 10:25 UTC, philip-khor commented
Thanks for clarifying!